import pandas as pd

# Create the comprehensive stock analysis framework data
data = {
    "Category": [
        "🟦 Basics", "🟦 Basics", "🟦 Basics", "🟦 Basics",
        "🟩 Ownership", "🟩 Ownership", "🟩 Ownership", "🟩 Ownership", "🟩 Ownership", "🟩 Ownership", "🟩 Ownership",
        "🟨 Valuation", "🟨 Valuation", "🟨 Valuation", "🟨 Valuation", "🟨 Valuation",
        "🟩 Quality", "🟩 Quality", "🟩 Quality", "🟩 Quality", "🟩 Quality", "🟩 Quality", "🟩 Quality",
        "🟥 Price", "🟥 Price", "🟥 Price",
        "🟪 Technical", "🟪 Technical", "🟪 Technical",
        "🟧 Risk", "🟧 Risk"
    ],
    "Column Name": [
        "Company Name", "Company Full Name", "Sector", "Market Cap Category",
        "Promoter Holding (%)", "Pledged Percentage (%)", "FII Holding (%)", "DII Holding (%)", "MF Holding (%)", "Holding Funds (Top 5)", "FII/DII Trend (3Q)",
        "PE Ratio", "Price-to-Book", "Price-to-Sales", "PEG Ratio", "Sector PE Comparison",
        "ROE (%)", "ROCE (%)", "Debt/Equity", "Rev. Growth (3Y)", "Profit Growth (3Y)", "Profit Margin (%)", "Operating Margin (%)",
        "Current Price", "52W High", "52W Low",
        "Price vs EMA (20/50/200)", "RSI (14)", "MACD Signal",
        "Beta", "Dividend Yield"
    ],
    "What is it? (Detailed Meaning)": [
        "Short identifier used in stock exchange (e.g., 'FORCEMOT', 'RBLBANK')",
        "Legal registered company name (e.g., 'Force Motors Limited', 'RBL Bank Limited')",
        "Industry type classification: IT, Pharma, Auto, Infrastructure, Banking, Chemicals, Textiles, etc.",
        "Classification based on company size: Small-cap (₹500–₹5,000 Cr), Micro-cap (<₹500 Cr), Mid-cap (₹5,000–₹20,000 Cr), Large-cap (>₹20,000 Cr)",
        "Percentage of total shares held by company founders/promoters (e.g., 55% means founders own 55% of company)",
        "Percentage of promoter shares pledged as collateral to lenders (e.g., 5% means 5% of promoter holdings are pledged). High pledge % = financial stress",
        "Percentage owned by Foreign Institutional Investors: hedge funds, pension funds, asset managers from US/Europe/Asia (e.g., BlackRock, Vanguard, Capital Group)",
        "Percentage owned by Domestic Institutional Investors: Indian mutual funds, insurance companies (LIC), pension funds (NPS), asset management companies",
        "Percentage owned by Mutual Funds (SBI Mutual Fund, HDFC MF, ICICI Prudential, Axis MF, etc.) — retail investors pool money here",
        "Names of top 5 institutional investors holding the stock (e.g., '1. HDFC Mutual Fund 2. SBI Mutual Fund 3. BlackRock 4. ICICI Prudential 5. Vishvaraj Trust')",
        "Trend showing whether FIIs and DIIs are buying (increasing %) or selling (decreasing %) over last 3 quarters",
        "Price per share ÷ Earnings per share (EPS). If PE = 20, you pay ₹20 for ₹1 annual profit",
        "Price per share ÷ Book Value per share (net assets). If P/B = 2, you pay ₹2 for ₹1 of net assets",
        "Price per share ÷ Revenue per share. If P/S = 3, you pay ₹3 for ₹1 annual sales",
        "PE Ratio ÷ Earnings Growth Rate. If PE = 25 and growth = 30%, PEG = 0.83",
        "Company's PE Ratio vs Industry/Sector Average PE. If company PE = 18 and sector avg = 25, it's 28% cheaper",
        "Net Profit ÷ Shareholder's Equity. If ROE = 20%, company generates ₹20 profit for every ₹100 owner capital",
        "Net Profit ÷ Total Capital Used (Equity + Debt). If ROCE = 25%, company generates ₹25 profit for ₹100 total capital",
        "Total Debt ÷ Shareholder's Equity. If D/E = 0.3, company has ₹30 debt for ₹100 owner capital",
        "Compound Annual Growth Rate (CAGR) of revenue over 3 years. If Rev 3Y CAGR = 18%, sales grew 18% annually",
        "CAGR of net profit over 3 years. If Profit 3Y CAGR = 25%, earnings grew 25% annually",
        "Net Profit ÷ Revenue × 100. If margin = 12%, company earns ₹12 profit for ₹100 sales",
        "Operating Profit (EBIT) ÷ Revenue × 100. Measures core business profitability before interest/tax",
        "Today's stock price (e.g., ₹1,847.50)",
        "Highest price stock reached in last 1 year (e.g., ₹2,150)",
        "Lowest price stock reached in last 1 year (e.g., ₹1,200)",
        "Price compared to Exponential Moving Averages: EMA-20 (20-day avg), EMA-50 (50-day), EMA-200 (200-day). If price ₹1,850 and EMA-200 = ₹1,600, price is above",
        "Momentum indicator (0–100). RSI = 70 = overbought, RSI = 30 = oversold. Calculated from recent price changes",
        "Trend/momentum indicator: MACD line crosses above Signal line = bullish, below = bearish. Histogram shows momentum strength",
        "Stock's volatility compared to market (Nifty). Beta = 1.5 = 50% more volatile than Nifty. Beta = 0.8 = 20% less volatile",
        "Annual dividend per share ÷ Current price × 100. If yield = 2%, you get ₹2/year for ₹100 investment"
    ],
    "Simple Meaning": [
        "Stock name/ticker",
        "Full legal identity",
        "Type of business the company does",
        "How big the company is",
        "How much the owners personally own",
        "How much owner capital is at risk (pledged)",
        "How much 'global smart money' owns",
        "How much 'Indian institutional money' owns",
        "How much 'retail via experts' owns",
        "Who exactly is investing in this company",
        "Recent institutional activity (last 9 months)",
        "How expensive the stock is relative to its profit",
        "Price vs company's net asset value",
        "Price vs company's revenue (sales)",
        "Valuation adjusted for growth rate",
        "How expensive stock is relative to peers",
        "Return on YOUR money (shareholder equity)",
        "True efficiency of entire business (owner + lender capital)",
        "How much the company is borrowing vs owning",
        "How fast sales are expanding",
        "How fast earnings are growing",
        "How profitable each ₹100 sale is",
        "Profitability of core operations (excluding one-offs)",
        "Current market value per share",
        "Recent peak value",
        "Recent bottom level",
        "Trend direction (short/medium/long-term)",
        "Is stock overbought (too high) or oversold (too low)?",
        "Is trend turning up or down?",
        "How risky/volatile the stock is",
        "Income return from stock (cash in pocket)"
    ],
    "Why It Matters": [
        "Helps identify stock quickly in databases, screener, trading platforms",
        "Avoid confusion between companies with similar ticker names; essential for legal research",
        "Sector determines growth potential, risk profile, regulatory environment, and cyclicality",
        "Determines risk level, liquidity, growth potential, and volatility",
        "Shows owner confidence, commitment, and alignment with shareholders. High promoter holding = less likelihood of fraudulent practices",
        "High pledge % = red flag (promoters borrowing against shares). Can signal cash stress or margin calls. >10% = concerning",
        "FIIs are sophisticated, research-driven investors. Rising FII = strong international demand, confidence in Indian growth story",
        "DIIs provide long-term stability, less volatile than FIIs. DII buying = steady domestic support even during FII selling",
        "Mutual funds employ professional analysts. MF buying = stock passed rigorous fundamental screening. High MF holding = liquidity + credibility",
        "Quality of investors matters more than quantity. Famous funds = credibility, research backing, long-term horizon",
        "Shows real accumulation — not just one-quarter noise. Consistent buying over 3 quarters = strong conviction, long-term bet",
        "Shows if stock is overvalued/undervalued. Higher PE = expensive, lower PE = cheap. But must consider growth rate",
        "Helps identify overvaluation, especially for asset-heavy companies (banks, infra, manufacturing). Low P/B = undervalued assets",
        "Used when profits are unstable/negative (growth companies). Sales are harder to manipulate than profits",
        "Best valuation metric — combines Price + Growth. Shows if high PE is justified by high growth",
        "Context matters — PE 20 is cheap if sector avg is 30, expensive if sector avg is 15",
        "Measures efficiency of using owner capital. High ROE = company creates value, low ROE = capital inefficient",
        "Best measure of business quality. ROCE > ROE = low debt (good). ROCE < ROE = high debt (risky)",
        "High debt = high risk (interest burden, bankruptcy risk). Low debt = financial strength, can survive downturns",
        "Shows business expansion and market demand. Consistent revenue growth = product/people want what you sell",
        "Wealth creation driver. Profit growth > revenue growth = improving efficiency (margin expansion)",
        "High margin = strong business (pricing power, efficiency, competitive advantage). Low margin = vulnerable to cost shocks",
        "Stable margin = consistency. Falling margin = cost pressure, competition, or inefficiency. Rising margin = scaling benefits",
        "Entry reference point. Alone meaningless — must compare with valuation, growth, peers",
        "Shows resistance level, strong demand. Near 52W high = momentum, bullish sentiment",
        "Shows support level, risk floor. Near 52W low = either opportunity (undervalued) or risk (downtrend)",
        "Shows trend strength. Above EMA-200 = long-term uptrend. Below = downtrend. EMA alignments predict breakouts/breakdowns",
        "Entry timing. RSI 70+ = wait for pullback. RSI 30– = wait for rebound. RSI 40–60 = ideal buying zone",
        "Entry confirmation. MACD bullish crossover = trend turning up. Bearish = trend turning down. Works with RSI for timing",
        "High beta = risky but high returns. Low beta = stable but lower returns. Small caps typically have high beta (1.2–2.0)",
        "Income vs growth tradeoff. High yield = stable business (mature). Low yield = growth company (reinvests profits)"
    ],
    "Good vs Bad Signal": [
        "— Neutral",
        "— Neutral",
        "Depends on sector: High growth: IT, Pharma, Specialty Chemicals ✅; Cyclical risk: Infra, Steel ⚠️",
        "Small = high risk, high growth; Large = low risk, stable growth",
        ">50% ✅ GOOD; <30% ⚠️ WARNING",
        "<3% ✅ SAFE; 3–10% ⚠️ CAUTION; >10% ❌ RED FLAG",
        "Increasing ✅ STRONG BUY; Decreasing ⚠️ SELL SIGNAL",
        "Increasing ✅ GOOD; Stable ✅ OK",
        "Increasing ✅ RESEARCHED DECISION; >20% ✅ HIGH CREDIBILITY",
        "Top famous funds ✅ BEST: HDFC MF, SBI MF, BlackRock, Vanguard",
        "Increasing over 3Q ✅ STRONGEST BUY; Decreasing ⚠️ AVOID",
        "10–25 ✅ GOOD RANGE; <10 ⚠️ Low growth trap; >40 ⚠️ Overvalued",
        "<3 ✅ GOOD; <1 ⚠️ Distress sale; >5 ⚠️ Overvalued",
        "Lower ✅ GOOD; <2 ✅ Cheap; >5 ⚠️ Expensive",
        "<1 ✅ BEST VALUE; 1–2 ✅ Fair; >2 ⚠️ Overvalued",
        "Lower than sector ✅ GOOD; Higher than sector ⚠️ Verify growth",
        ">15% ✅ GOOD; >20% ✅ EXCELLENT; <10% ⚠️ Poor",
        ">20% ✅ EXCELLENT; 15–20% ✅ GOOD; <12% ⚠️ Poor",
        "<0.5 ✅ SAFE; 0.5–1 ⚠️ Moderate; >1 ⚠️ RISKY; >2 ❌ AVOID",
        ">10% ✅ GOOD; >15% ✅ STRONG; >20% ✅ EXCEPTIONAL; <5% ⚠️ Stagnant",
        ">15% ✅ GOOD; >20% ✅ STRONG; >30% ✅ EXCEPTIONAL; <10% ⚠️ Slow",
        "Higher ✅ BETTER; >15% ✅ EXCELLENT; 10–15% ✅ GOOD; <5% ⚠️ Thin margin",
        "Stable ✅ GOOD; Rising ✅ EXCELLENT; Falling ⚠️ WARNING",
        "— Neutral (price alone tells nothing)",
        "Near 52W High ✅ STRONG DEMAND; >20% below high ⚠️ Weak",
        "Near 52W Low ⚠️ RISK or OPPORTUNITY",
        "Above 200 EMA ✅ LONG-TERM UPTREND; Above 50 EMA ✅ MEDIUM TREND; Below 200 EMA ⚠️ DOWNTREND",
        "40–60 ✅ IDEAL BUYING RANGE; >70 ⚠️ Overbought (wait); <30 ⚠️ Oversold (wait for rebound)",
        "Bullish crossover ✅ BUY; Bearish crossover ⚠️ SELL/AVOID",
        "<1 ✅ LOW RISK; 1–1.5 ⚠️ Moderate; >1.5 ⚠️ HIGH RISK (normal for small caps)",
        "Moderate ✅ GOOD (1–3%); >4% ✅ STABLE BUSINESS; <1% ⚠️ Growth company"
    ],
    "How to Use It Practically": [
        "Just reference this when searching stocks on Screener.in, NSE/BSE websites",
        "Use for deep research on MCA (Ministry of Corporate Affairs), annual reports, press releases",
        "Compare only within same sector — never compare Pharma PE with Auto PE. Use sector averages for valuation benchmarking",
        "Small caps for growth (10X potential but volatile); Large caps for stability (5–10% returns, safe). For your focus: Small/Micro caps where FII+MF buying = asymmetric opportunity",
        "Look for promoters holding 50–70% (sweet spot). Avoid >80% (too concentrated) or <30% (promoters don't care). Check if promoter holding is increasing over quarters",
        "Check quarterly pledging from NSE/BSE disclosures. If pledge increases from 2% → 8%, it's a warning (cash flow stress). Avoid stocks with >5% pledge. This is a hard stop signal if >10%",
        "Rising FII = strongest institutional signal. Check 3–4 quarter trend. For small caps: FII >5% is significant. If FII increased from 3% → 7% in 4 quarters, it's a gem signal",
        "DII buying = steady support. In FII selling periods (like 2022–2023), DII buying kept markets alive. Look for DII >15% for stability",
        "MF buying = professional stock selection. Check if top 5 MFs are buying. If HDFC MF + SBI MF both increased holdings, it's validated. For small caps: MF >10% is strong",
        "Famous funds = credibility. If 'HDFC Mutual Fund' holds 8% and increased from 5%, it's validated. Avoid obscure funds. Check fund manager's track record",
        "This is the #1 buy signal. Check quarterly shareholding patterns on NSE/BSE. If FII: 4% → 5.5% → 7% (3 quarters), it's institutional accumulation. For small caps, this is gem-level signal",
        "Compare with growth: PE 25 is fine if profit growth is 30%. PE 15 is bad if growth is 5%. Use PEG Ratio (PE ÷ Growth) for better view. For small caps: PE 15–30 acceptable if ROE >15%",
        "Good for banks/infra/manufacturing. For RBL Bank: P/B 1.5 = cheap. For IT/Pharma (asset-light): P/B less relevant. Use PE + ROE for those",
        "For growth companies (early-stage, high expansion). If P/S = 1.5 and revenue growing 25% YoY, it's attractive. For established firms: use PE",
        "PEG <1 = gem. Example: PE 20, growth 30% → PEG 0.67 = undervalued. PE 40, growth 15% → PEG 2.67 = overvalued. Use PEG for small caps",
        "Cheap vs peers = opportunity. If Pharma sector PE = 35 and your stock PE = 22 with similar ROE, it's undervalued. Always compare with 3–5 peers",
        "Higher = better company. For small caps: ROE >15% is minimum. Check 3-year trend (consistent >15% = quality). ROE 25%+ = exceptional (e.g., Luxury brands, Specialty chemicals)",
        "Especially for infra/industrial/manufacturing. ROCE 25%+ = world-class (e.g., Titan, Nestle). For small caps: ROCE >18% is quality. Check 5-year trend",
        "Avoid high debt stocks. For small caps: D/E <0.3 is ideal. Debt-free companies preferred. Exception: Banks (high leverage = business model), Infra (temporary debt for projects)",
        "Indicates demand. Check 3-year consistency (not one-year spike). For small caps: Rev growth 15–25% = growth phase. >30% = hypergrowth (verify sustainability)",
        "Most important growth metric. Stock prices follow profits long-term. For small caps: Profit growth 20–35% = gem potential. Check if profit growth > revenue growth (margin improvement)",
        "Shows pricing power. Specialty chemicals: 15–25% margin = quality. Manufacturing: 8–12% normal. Retail: 3–7% normal. Trend matters: margin expanding = improving efficiency",
        "Falling margin = red flag. Check 3-year trend. If Op Margin 18% → 16% → 14%, investigate (cost rise? price cut?). Stable 15–17% = predictable business",
        "Ignore price alone. ₹100 stock can be expensive (PE 50), ₹5,000 stock can be cheap (PE 12). Focus on PE, ROE, growth",
        "Near high = momentum play. If price ₹2,050 and 52W high ₹2,150 (5% below), it's in uptrend. Breakout above 52W high = new leg up. Use for timing entry",
        "Context matters: Near low + FII buying + ROE 20% = opportunity. Near low + debt 2.0 + margin falling = value trap. Check fundamentals before buying near low",
        "Long-term buy above 200 EMA. For small caps: Price > EMA-50 > EMA-200 = strong uptrend (golden cross). Price < EMA-50 < EMA-200 = downtrend (death cross). Use for entry timing",
        "Ideal buy: RSI 45–55. If RSI 68 and FII buying + ROE 22%, wait for RSI dip to 50 then buy. For small caps: RSI >75 = short-term top, RSI <25 = short-term bottom",
        "Buy when MACD turns up. If MACD crosses above signal line + price above 200 EMA + FII buying = strong entry. Wait for MACD bullish for small cap entries",
        "Small caps often high beta (1.3–1.8). Accept for growth. If beta 2.0+ and debt 1.5+, avoid (double risk). Use stop-loss for high-beta stocks",
        "High yield = stable business (banks, utilities). For small caps: 1–2% yield normal. >3% = mature/stable. Don't chase yield >5% (often value trap)"
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Save to Excel file
excel_file_path = "Stock_Analysis_Framework_Complete.xlsx"
df.to_excel(excel_file_path, index=False)

print(f"Excel file created successfully: {excel_file_path}")
print(f"Total rows: {len(df)}")
print(f"Total columns: {len(df.columns)}")